### ISSUE TITLE
Translation History

### ISSUE THREAD

**Issue by javipacheco** [47deg/translate-bubble-android#8]
We should save all translations in a local database for the user can consult later.

The information that we have to save is:

* Original text
* Translated text
* Languages

In the Preferences Screen we have to add a new section called "Translation History" where the user can see all translations sorted by date

Developer notes:

* Should use [Content Provider](http://developer.android.com/guide/topics/providers/content-provider-creating.html)
* Should create a new module using [Cake Pattern](http://jonasboner.com/2008/10/06/real-world-scala-dependency-injection-di/) like others [modules](https://github.com/47deg/translate-bubble-android/tree/master/src/main/scala/com/fortysevendeg/translatebubble/modules) in the project 
* [Material desing](http://www.google.es/design/spec/components/lists.html#lists-content) is appreciated

**Comment by franciscodr** [comment]
This new feature has been implemented within the pull request https://github.com/47deg/translate-bubble-android/pull/22
